#! /bin/sh

# Run xmodmap to load keymappings
xmodmap ~/.Xmodmap

# Load background image
~/.fehbg

# Start Compositor
compton &

# Start Bar
~/.config/polybar/launch.sh &


# Hotkeys
killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 0

bspc config border_width			4
bspc config window_gap				0
bspc config focus_follows_pointer	true

bspc config focused_border_color	\#0B76DE
bspc config normal_border_color		\#181818

bspc config split_ratio			0.50
bspc config borderless_monocle	true
bspc config gapless_monocle		true

bspc rule -a Gimp state=floating follow=on
