#!/bin/sh

bspc wm -g | awk -F'[:]' '{print $2, $3, $4, $5, $6}' | {
	read -r desk1 desk2 desk3 desk4 desk5

	OUTPUT="{reset}{font=3} {font=0}  "
	for i in {1..5}; do
		DESKSTATUS="$(eval "echo \$desk$i")"
		DESKSTATUS="${DESKSTATUS:0:1}"

		if [ $DESKSTATUS = "O" ] || [ $DESKSTATUS = "F" ] || [ $DESKSTATUS = "U" ] ; then
			OUTPUT="$OUTPUT  "
		
		elif [ $DESKSTATUS = "o" ] || [ $DESKSTATUS = "u" ]; then
			OUTPUT="$OUTPUT  "

		elif [ $DESKSTATUS = "f" ]; then
			OUTPUT="$OUTPUT  "
		fi
	done

	OUTPUT="$OUTPUT{reset}"
	rrnotify $OUTPUT
}
